/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\public\models\astro.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Astro = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    '../../public/models/astro.glb',
  )
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature">
          <primitive object={nodes.Root} />
          <skinnedMesh
            name="Astronaut"
            geometry={nodes.Astronaut.geometry}
            material={materials.Astronaut}
            skeleton={nodes.Astronaut.skeleton}
          />
        </group>
      </group>
    </group>
  )
}
export default Astro

useGLTF.preload('../../public/models/astro.glb')
